export const data = {
  csvRowsToArray: null,
  level: 1,
  guessedWordsInRow: 0,

  set setCsvRowsToArray(value) {
    this.csvRowsToArray = value;
  },
  set setLevel(value) {
    this.level = value;
  },
  set setGuessedWordsInRow(value) {
    this.guessedWordsInRow = value;
  }
};

export const allCityStates = [' CIVILIZATION_ARMAGH', ' CIVILIZATION_BOLOGNA', ' CIVILIZATION_VATICAN_CITY', ' CIVILIZATION_RAPA_NUI', ' CIVILIZATION_PALENQUE', ' CIVILIZATION_TARUGA', ' CIVILIZATION_LISBON', ' CIVILIZATION_MUSCAT', ' CIVILIZATION_KANDY', ' CIVILIZATION_ZANZIBAR', ' CIVILIZATION_NGAZARGAMU', ' CIVILIZATION_AYUTTHAYA', ' CIVILIZATION_BRUSSELS', ' CIVILIZATION_LAHORE', ' CIVILIZATION_NAZCA', ' CIVILIZATION_AUCKLAND', ' CIVILIZATION_ANTIOCH', ' CIVILIZATION_PRESLAV', ' CIVILIZATION_SINGAPORE', ' CIVILIZATION_MOHENJO_DARO', ' CIVILIZATION_AKKAD', ' CIVILIZATION_GRANADA', ' CIVILIZATION_LA_VENTA', ' CIVILIZATION_FEZ', ' CIVILIZATION_SAMARKAND', ' CIVILIZATION_WOLIN', ' CIVILIZATION_NALANDA', ' CIVILIZATION_BABYLON', ' CIVILIZATION_JOHANNESBURG', ' CIVILIZATION_ANTANANARIVO', ' CIVILIZATION_CAHOKIA', ' CIVILIZATION_YEREVAN', ' CIVILIZATION_JERUSALEM', ' CIVILIZATION_CAGUANA', ' CIVILIZATION_NAN_MADOL', ' CIVILIZATION_BUENOS_AIRES', ' CIVILIZATION_JAKARTA', ' CIVILIZATION_MEXICO_CITY', ' CIVILIZATION_VALLETTA', ' CIVILIZATION_HATTUSA', ' CIVILIZATION_GENEVA', ' CIVILIZATION_KUMASI', ' CIVILIZATION_HONG_KONG', ' CIVILIZATION_CARDIFF', ' CIVILIZATION_CHINGUETTI', ' CIVILIZATION_VILNIUS', ' CIVILIZATION_KABUL', ' CIVILIZATION_HUNZA', ' CIVILIZATION_FREE_CITIES'];